server:
  port: 8080
---

#spring:
#  profiles: default
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/petfriends?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: root
    
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true #To beautify or pretty print the SQL
#        show_sql: true #show sql

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

    
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Walk
          destination: petfriends
          contentType: application/json
        event-out:
          destination: petfriends
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
    org.springframework.cloud: debug
server:
  port: 8080
  #port: 8089
